version: 2

jobs:
  build:
    docker:
      - image: nixos/nix
    working_directory: ~/rules_haskell
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk --no-progress update
            apk --no-progress add bash ca-certificates
            nix-channel --update
            nix-env -iA nixpkgs.bazel nixpkgs.binutils nixpkgs.python
      - run:
          name: Build
          command: bazel build --jobs=2 //...
      - run:
          name: Run tests
          command: bazel test //...
      - run:
          name: Test some package repositories
          command: |
              bazel build --jobs=2 \
                  @haskell_{aeson,language-c,lens,old-time,network}//...
