version: 2

jobs:
  build:
    docker:
      - image: nixos/nix:1.11.14
    working_directory: ~/rules_haskell
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk --no-progress update
            apk --no-progress add bash ca-certificates
            REVISION=8d5f06cbeedcfb4a88c111754baf2d7e315e74de
            nix-env -f https://github.com/NixOS/nixpkgs/archive/$REVISION.tar.gz \
              -iA bazel binutils python git
      - run:
          name: Build
          command: bazel build --jobs=2 //...
      - run:
          name: Run tests
          command: bazel test //...
      - run:
          name: Test some third-party packages
          command: |
              bazel build --jobs=2 \
                  $(for p in $(cat test-packages.txt)
                    do
                       echo @haskell_$p//...
                    done)
